# Generated by Django 5.0.7 on 2024-08-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
    ]
