# Generated by Django 5.0.8 on 2024-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(max_length=255)),
                ('bool_input', models.BooleanField()),
                ('pdf_input', models.FileField(upload_to='pdf/')),
                ('photo_input', models.ImageField(upload_to='img/')),
                ('csv_input', models.ImageField(upload_to='csv/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
