# Generated by Django 4.1.13 on 2024-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='csv_input',
            field=models.FileField(upload_to='csvs/'),
        ),
    ]
