flowchart TD
    A[Raw Signals Collected] --> B[Signal Grouping]
    B --> B1[Grouping Window: 10  Polling Interval: 1 minute]
    B1 --> C[Grouped Signals]
    C --> D[Store in: Redis Chache]
    E --> E1[Correlation Engine Default Rules + Custom Rules + AI Generated Rules]
    D --> E[Uses correlation rules Rules are built using signal patterns and topology relationships]
    E1 --> F[Correlated Event Detected]
    F --> G[Store in: rca-correlated-index]
    G --> H[RCA Engine]
    H --> I[Source Dependency Graph Analysis]
    I --> J[Confidence Score Calculation]
    J --> K{Is confidence score > 7?}
    K --> |yes| L[Send the Data to LLM and get the response for the root cause ]
    L --> M[Create RCA record in RCA index]
    M --> N[Link RCA to the corresponding existing event]
    K -->|No| P[Mark as Probable Cause]
    P --> Q[Link to a event and save it in a RCA index]
    O[Confidence Factors Used] --> O1[1. Sequence Match
2. Dependency Match
3. Time Proximity
4. Signal Severity
5. Rule Completeness]
    O1 -. influences .-> J