// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';

export function ApplyChanges(arg1:contracts.ApplyChangesModel):Promise<Record<string, any>>;

export function CherryPick(arg1:contracts.CherryPickRequestModel):Promise<Record<string, any>>;

export function CommitAndPush(arg1:contracts.CommitAndPushRequestModel):Promise<Record<string, any>>;

export function DeleteSecret(arg1:string):Promise<Record<string, any>>;

export function GenerateChanges(arg1:contracts.ConfigModel):Promise<Record<string, any>>;

export function GetApprovalPreview(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetFeatureContext(arg1:contracts.PRFeatureContextRequestModel):Promise<Record<string, any>>;

export function GetJob(arg1:string):Promise<Record<string, any>>;

export function GetSettings():Promise<Record<string, any>>;

export function GetUsageMetrics():Promise<Record<string, any>>;

export function GetWorkItemFamily(arg1:contracts.PRWorkItemFamilyRequestModel):Promise<Record<string, any>>;

export function Health():Promise<Record<string, any>>;

export function ListChangedFiles(arg1:contracts.PRWorkflowBaseRequestModel):Promise<Record<string, any>>;

export function ListReviewers(arg1:contracts.PRReviewersRequestModel):Promise<Record<string, any>>;

export function ProceedJob(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RaiseNewPR(arg1:contracts.RaiseNewPRRequestModel,arg2:boolean):Promise<Record<string, any>>;

export function ReviewDiffs(arg1:contracts.ConfigModel,arg2:boolean):Promise<Record<string, any>>;

export function RunFullReview(arg1:contracts.ConfigModel,arg2:boolean):Promise<Record<string, any>>;

export function RunStaticChecks(arg1:contracts.StaticChecksRequestModel,arg2:boolean):Promise<Record<string, any>>;

export function SaveSettings(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SetSecret(arg1:string,arg2:string):Promise<Record<string, any>>;
