// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChanges(arg1) {
  return window['go']['desktop']['App']['ApplyChanges'](arg1);
}

export function CherryPick(arg1) {
  return window['go']['desktop']['App']['CherryPick'](arg1);
}

export function CommitAndPush(arg1) {
  return window['go']['desktop']['App']['CommitAndPush'](arg1);
}

export function DeleteSecret(arg1) {
  return window['go']['desktop']['App']['DeleteSecret'](arg1);
}

export function GenerateChanges(arg1) {
  return window['go']['desktop']['App']['GenerateChanges'](arg1);
}

export function GetApprovalPreview(arg1, arg2) {
  return window['go']['desktop']['App']['GetApprovalPreview'](arg1, arg2);
}

export function GetFeatureContext(arg1) {
  return window['go']['desktop']['App']['GetFeatureContext'](arg1);
}

export function GetJob(arg1) {
  return window['go']['desktop']['App']['GetJob'](arg1);
}

export function GetSettings() {
  return window['go']['desktop']['App']['GetSettings']();
}

export function GetUsageMetrics() {
  return window['go']['desktop']['App']['GetUsageMetrics']();
}

export function GetWorkItemFamily(arg1) {
  return window['go']['desktop']['App']['GetWorkItemFamily'](arg1);
}

export function Health() {
  return window['go']['desktop']['App']['Health']();
}

export function ListChangedFiles(arg1) {
  return window['go']['desktop']['App']['ListChangedFiles'](arg1);
}

export function ListReviewers(arg1) {
  return window['go']['desktop']['App']['ListReviewers'](arg1);
}

export function ProceedJob(arg1, arg2) {
  return window['go']['desktop']['App']['ProceedJob'](arg1, arg2);
}

export function RaiseNewPR(arg1, arg2) {
  return window['go']['desktop']['App']['RaiseNewPR'](arg1, arg2);
}

export function ReviewDiffs(arg1, arg2) {
  return window['go']['desktop']['App']['ReviewDiffs'](arg1, arg2);
}

export function RunFullReview(arg1, arg2) {
  return window['go']['desktop']['App']['RunFullReview'](arg1, arg2);
}

export function RunStaticChecks(arg1, arg2) {
  return window['go']['desktop']['App']['RunStaticChecks'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['desktop']['App']['SaveSettings'](arg1);
}

export function SetSecret(arg1, arg2) {
  return window['go']['desktop']['App']['SetSecret'](arg1, arg2);
}
