# Generated by Django 5.0.7 on 2024-08-01 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_blogpost_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='name',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 1, 54, 43, 649651, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
