batch_size: 64
height: 32
learning_rate: 0.002
max_text_length: 21
model_path: D:\Code for tutorials\Machine Learning\saved_models\handwriting_recognition_torch\202506250501
train_epochs: 1000
vocab: '!"#&''()*+,-./0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
width: 128
